#!/bin/sh

usage() {
  echo "usage: $0 <session name> <user>"
}

if [ "$2" = "" ] ; then
  usage
  exit 0
fi

#PAIRDIR=/tmp/${USER}.pair
PAIRDIR=/tmp/pair-cobbler
if [ ! -d  "$PAIRDIR" ] ; then
  mkdir -p "$PAIRDIR"
  echo "Go start a session under $PAIRDIR"
  exit 1
fi

cd $PAIDIR

ln -fs "$1" "$2".pairssh

echo -n "Set permissions on shared session (y|N)? "
read resp
if [ "$resp" = "y" -o "$resp" = "Y" ] ; then
  chmod 666 ${PAIRDIR}/$1
else
  echo "Go set the correct permissions on ${PAIRDIR}"
fi
